name: CI-CD_Pipeline-To-Server
#csdc
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@91.107.121.130 "bash -s" << 'EOF'
          cd ~/path
          git pull origin main
          # Additional commands to build/restart your application
          sudo systemctl restart your-app.service
        EOF
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
